### ISSUE TITLE
[BUG]: the <host-source> and <scheme-source> must not be wrapped in quotes

### ISSUE THREAD

**Issue by czabaj** [josh-hemphill/csp-typed-directives#3]
### Description

I'm using the [vite-plugin-csp](https://github.com/josh-hemphill/vite-plugin-csp#readme) and it's currently buggy for me for it is wrapping the specified URL's in single quotes, which is not valid (according to [MDN CSP documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src)) and it is also ignored by the browser (Chrome 93.0.4577.63).

I believe the problem is on [this LOC](https://github.com/josh-hemphill/csp-typed-directives/blob/latest/src/index.ts#L94), the wrapping is done for all the sources, but it must be applied only to some of them.

Given how complicated the syntax for `<host-source>` might be, I would probably go for testing all keywords and crypto sources, rather than testing `<host-source>` and `<scheme-source>`.

Something like

```JavaScript
const applyQuoteRe = new RegExp(
  `^(nonce-.+|none|report-sample|self|strict-dynamic|unsafe-eval|unsafe-hashes|unsafe-inline|${hashAlgorithms.join('-.+|')}-.+)$`
);
```

might do the job, but this rule applies not only to `script-src`, but also to `style-src` and probably more policies and there might be more keywords specified for other policies, which I'm unaware of, as I'm a newbie in terms of CSP. So you might opt-out for testing the `<host-source>` and `<scheme-source>`, just beware that testing the URI of `<host-source>` might be very complicated as the CSP allows to use wildcards and omit the scheme, thus the Node js URL cannot be used.

**Comment by josh-hemphill** [comment]
I'll try and get this fixed. Though [vite-plugin-csp](https://github.com/josh-hemphill/vite-plugin-csp#readme) is still unfinished, I'm now looking at rewriting it in a monorepo containing some shared functionality to provide SSG and framework specific SSR plugins/libraries so that it things like CSP nonces can be used and hashes be accurate to the files provided at various paths, all of which aren't really possible through only the build hooks currently.

**Comment by josh-hemphill** [comment]
Still need to update vite-plugin-csp, but I should be able to get to that tomorrow. 🤞

**Comment by josh-hemphill** [comment]
@czabaj I've updated vite-plugin-csp, ran into some typing issues and it took a little longer. Should be good now.

**Comment by czabaj** [comment]
Thanks @josh-hemphill 

just tested it and there must be an issue in the linaria plugin as well. The URIs are still quoted

See

<img width="610" alt="Screenshot 2021-10-11 at 10 21 48" src="https://user-images.githubusercontent.com/47554112/136757455-7505896a-3f94-4036-b35d-adaba17fcc0f.png">
<img width="536" alt="Screenshot 2021-10-11 at 10 23 21" src="https://user-images.githubusercontent.com/47554112/136757475-94a1b7e8-d3dc-44b7-b6df-cdb2e2bf6843.png">

![Screenshot 2021-10-11 at 10 23 45](https://user-images.githubusercontent.com/47554112/136757549-16877854-328f-4e0e-8301-686e578b77b1.png)
![Screenshot 2021-10-11 at 10 24 02](https://user-images.githubusercontent.com/47554112/136757568-821c2acd-8e0f-4427-aa7f-87245ff638c7.png)

**Comment by josh-hemphill** [comment]
Yep, I just went through and double checked the output of vite-plugin-csp, and it seems to be correct there. Though I'm not sure how another plugin would introduce quoting to the internal values of meta strings...
